/**
 * 앱 전체 한국어 UI 문자열을 탭/컴포넌트별로 관리합니다.
 * 하드코딩 대신 이 파일을 import해서 사용하세요.
 *
 * import { TEXTS } from '@/config/texts'
 */

export const TEXTS = {
  // ────────────────────────────────────────
  // 홈탭 — AiInputBox
  // ────────────────────────────────────────
  ai: {
    placeholder: '오늘 소비 내역을 알려줘!',
    placeholderFull: '오늘 소비 내역을 알려줘!\n예) 아아 삼천원\n예) 스벅 6천원 배민 치킨 18000원',
    btnAnalyze: 'AI 분류',
    btnAnalyzing: '분석 중',
    recognized: (n: number) => `${n}건 인식됨 — 확인 후 저장하세요`,
    btnSaveAll: (n: number) => `${n}건 전체 저장`,
    btnSave: '저장',
    btnSaving: '저장 중...',
    btnCancel: '취소',
    btnRetry: '다시 시도',
    btnEdit: '✏️ 수정',
    btnFold: '접기',
    btnDelete: '삭제',
    labelIncome: '수입',
    labelExpense: '지출',
    labelCategory: '카테고리',
    labelPayment: '결제수단',
    labelIncomeSource: '수입 경로',
    labelPaymentExpense: '지출수단',
    failTitle: '인식에 실패했어요',
    failSubtitle: '여기서 바로 입력할 수 있어요',
    failSaved: '✓ 저장됐어요!',
    failSaving: '저장 중...',
    failBtnSave: '저장하기',
    inlineAmount: '금액 *',
    inlineName: '항목명 *',
    inlineAmountPlaceholder: '0',
    inlineNamePlaceholder: '예) 스타벅스',
    saveErrorRetry: '저장 중 오류가 발생했어요.',
    saveErrorPersist: '저장에 계속 실패하고 있어요. 직접 입력 탭을 이용해주세요.',
    saveErrorNetworkRetry: '네트워크 오류가 발생했어요.',
    saveErrorNetworkPersist: '저장에 계속 실패하고 있어요. 직접 입력 탭을 이용해주세요.',
    linkManualInput: '직접 입력하러 가기 →',
    networkError: '네트워크 오류',
  },

  // ────────────────────────────────────────
  // 홈탭 — DashboardHeader
  // ────────────────────────────────────────
  header: {
    greetingPrefix: '안녕하세요, ',
    greetingSuffix: '님!',
    defaultName: '소비요정',
    subtitle: '오늘도 현명한 소비 습관을 만들어봐요.',
    totalSpent: '이번 달 총 지출',
    savingGoal: '저축 목표',
    savingProgress: '저축 진행률',
    goalMet: '🎉 목표 달성!',
    savingPct: (pct: number, saved: number) => `${pct}% (${saved.toLocaleString()}원)`,
  },

  // ────────────────────────────────────────
  // 자산탭 — AssetsClient
  // ────────────────────────────────────────
  assets: {
    title: '자산',
    sectionIncome: '월 수입',
    sectionIncomeNotSet: '미설정',
    sectionBudget: '예산',
    budgetNotSet: '미설정',
    budgetSet: (total: number) => `총 ${total.toLocaleString()}원 설정`,
    sectionAccount: '계좌 / 현금',
    totalBalance: (v: number) => `총 잔액 ${v.toLocaleString()}원`,
    sectionCard: '카드',
    cardCount: (n: number) => `${n}개 등록`,
    cardNone: '미등록',
    sectionFixed: '고정비',
    fixedMonthly: (v: number) => `월 ${v.toLocaleString()}원 지출`,
    bannerTitle: '🏦 자산 설정을 완성해봐요!',
    bannerDesc: '계좌·카드·고정비를 등록하면 가계부가 완성돼요',
    noAccounts: '등록된 계좌가 없어요',
    noCards: '등록된 카드가 없어요',
    noFixedExpense: '고정 지출이 없어요',
    noFixedSaving: '고정 저축이 없어요',
    incomeLabel: '월 수입 (세후)',
    savingGoalLabel: '저축 목표 (선택)',
    incomeSuffix: '원',
    btnSave: '저장',
    btnCancel: '취소',
    btnEdit: '✏️ 수정',
    btnAddCash: '💵 현금 추가',
    btnAddAccount: '+ 계좌 추가',
    btnAddCard: '+ 카드 추가',
    btnDelete: '삭제',
    btnPay: '납부 기록',
    cardNoExpense: '이 카드로 결제한 내역이 없어요',
    cardMonthTotal: (v: number) => `이번달 합계 ${v.toLocaleString()}원`,
    cardPayStatus: {
      done: '✓ 완료',
      today: '오늘 납부일 ⚠️',
      late: '지연 ⚠️',
      dDay: (d: number) => `D-${d}`,
    },
    dueDatePer: (day: number) => `매월 ${day}일`,
    cashForm: {
      title: '💵 현금 추가',
      placeholder: '보유 현금 잔액',
      suffix: '원',
      btnAdd: '등록',
      btnCancel: '취소',
    },
    cardPaySheet: {
      title: (name: string) => `${name} 납부 기록`,
      subtitle: (day: number) => `매월 ${day}일 납부`,
      tip: '💡 카드사 앱에서 이번 달 청구 금액을 확인해보세요',
      labelAmount: '납부 금액 *',
      labelDate: '납부일',
      labelMemo: '메모 (선택)',
      memoPh: '간단히 남겨보세요',
      amountPh: '0',
      amountPrefix: '납부금액',
      errAmount: '금액을 입력해주세요',
      btnCancel: '취소',
      btnSave: '기록하기',
      btnSaving: '기록 중...',
      toast: '기록됐어요 ✓',
    },
    fixedSection: {
      expense: '고정 지출',
      saving: '고정 저축',
      btnAdd: '+ 추가',
      subtotal: (v: number) => `소계 ${v.toLocaleString()}원`,
      subtotalSaving: (v: number) => `소계 ${v.toLocaleString()}원`,
    },
    editFixed: {
      namePh: '이름',
      amountPh: '금액',
      duePh: '출금일',
      btnSave: '저장',
      btnCancel: '취소',
    },
    inline: {
      selectPh: '선택',
      btnSave: '저장',
      btnCancel: '취소',
    },
    incomeError: (msg: string) => `저장 실패: ${msg}`,
    fieldNames: {
      accountName: '계좌명',
      bank: '은행',
      balance: '잔액',
      accountType: '유형',
      cardName: '카드명',
      dueDay: '대금 출금일',
      linkedAccount: '연결 계좌/카드',
      fixedName: '이름',
      fixedAmount: '금액',
      fixedDueDay: '빠져나가는 날',
      linkedSource: '출금 계좌 (돈이 나가는 곳)',
      linkedTarget: '입금 계좌 (적금 계좌)',
    },
    placeholders: {
      accountName: '예) 국민 주거래통장',
      bank: '예) KB국민',
      balance: '0',
      cardName: '예) 신한카드',
      cardBank: '예) 신한',
      dueDay: '예) 15',
      fixedName: '예) 넷플릭스',
      fixedDueDay: '예) 25',
      savingDueDay: '예) 5',
    },
  },

  // ────────────────────────────────────────
  // 고정비탭 — FixedCostList
  // ────────────────────────────────────────
  fixed: {
    noItems: (kind: string) => `등록된 ${kind} 항목이 없어요.`,
    dueDateLabel: (day: number) => `매월 ${day}일`,
    btnAdd: (kind: string) => `+ ${kind} 추가`,
    btnCancel: '취소',
    btnSave: '추가',
    btnSaving: '저장 중…',
    formNamePh: (kind: string) => kind === '고정저축' ? '항목명 (예: 청약통장, 적금)' : '항목명 (예: 넷플릭스, 월세)',
    formAmountPh: '금액',
    formDuePh: '이체일 (선택, 숫자만)',
    // ApplyFixedCosts
    apply: {
      doneTitle: (n: number) => `이번 달 고정비가 모두 반영됐어요 (${n}건)`,
      pendingTitle: '이번 달 고정비 반영',
      pendingDesc: (n: number, total: number) => `${n}건 미반영 · ${total.toLocaleString()}원`,
      btnApply: '지출에 반영',
      btnApplying: '반영 중...',
    },
  },

  // ────────────────────────────────────────
  // 예산탭 — BudgetForm
  // ────────────────────────────────────────
  budget: {
    tabManual: '✏️ 직접 입력',
    tabAI: '✨ 스마트 추천',
    incomeBasis: (income: number) => `월 수입 ${income.toLocaleString()}원 기준`,
    fixedSavingNote: (v: number) => `고정저축 ${v.toLocaleString()}원 반영됨`,
    assetLinkNote: '에서 월 수입을 입력하면 더 정확해요',
    spendBudget: (v: number) => `지출 ${v.toLocaleString()}원`,
    savingPlanTitle: '💚 저축 플랜',
    savingTarget: '목표 저축',
    savingFixed: '고정저축 (이미 확보)',
    savingExtra: '추가 저축 목표',
    distTitle: '📊 지출 예산 배분',
    totalProgress: '전체 예산 달성률',
    spentLabel: (v: number) => `지출 ${v.toLocaleString()}원`,
    budgetLabel: (v: number) => `예산 ${v.toLocaleString()}원`,
    placeholderAmount: '예산 미설정',
    unitWon: '원',
    btnAIRecommend: '✨ 내 소비패턴 기반 AI 맞춤 추천',
    btnAILoading: '내 소비 패턴 분석 중...',
    btnSavePlan: '이 플랜으로 저장하기',
    btnSavePlanSaved: '✓ 저장됨',
    btnSavePlanSaving: '저장 중...',
    btnSaveManual: '예산 저장하기',
    btnSaveManualSaved: '✓ 저장됨',
    btnSaveManualSaving: '저장 중...',
    noSet: '미설정',
    spentNoExpense: '지출 없음',
    spentAmount: (v: number) => `지출 ${v.toLocaleString()}원`,
    toastNoIncome: '자산 탭에서 월 수입을 먼저 입력해주세요',
    toastAIDone: 'AI 예산 추천이 완료됐어요',
    assetTabName: '자산 탭',
  },

  // ────────────────────────────────────────
  // 설정탭 — SettingsForm
  // ────────────────────────────────────────
  settings: {
    sectionAccount: '👤 계정',
    sectionCategory: '📂 카테고리',
    sectionTheme: '🎨 테마',
    sectionNotif: '🔔 알림',
    sectionDisplay: '🖼️ 디스플레이',
    sectionExport: '📤 데이터 내보내기',
    sectionInfo: 'ℹ️ 앱 정보',
    sectionDanger: '⚠️ 계정 관리',
    labelLoginMethod: '로그인 방식',
    labelAccount: '계정',
    labelCategoryManage: '카테고리 관리',
    labelAppGuide: '앱 가이드 다시 보기',
    labelVersion: '버전',
    guestAccount: '게스트 계정',
    guestLabel: '👤 게스트',
    labelHomeGif: '홈 화면 움직이는 이미지',
    labelHomeGifDesc: 'GIF 재생 켜기/끄기',
    premiumOnly: '🔒 프리미엄',
    premiumUpgradeNote: '프리미엄에서 홈 화면을 나만의 이미지/GIF로 꾸밀 수 있어요',
    exportDesc: '지출/수입 내역을 CSV 파일로 내보내 엑셀 등에서 분석할 수 있어요',
    exportBtnPremium: '🔒 프리미엄 전용',
    exportBtnDownload: '📥 CSV 다운로드',
    exportLoading: '내보내는 중...',
    periodThisMonth: '이번 달',
    periodLast3: '최근 3개월',
    periodAll: '전체 기간',
    themeBasic: '기본',
    themePremium: '프리미엄 ✨',
    themeApplied: '적용 중 ✓',
    themeComing: '준비중',
    notifAll: '전체 알림',
    notifSubscribed: '✓ 알림 구독 중',
    notifOn: '켜짐',
    notifOff: '꺼짐',
    notifCardRemind: '💳 카드 · 고정비 납부 리마인드',
    notifDueRemind: '출금일 리마인드 알림',
    notifDueDesc: '출금일 D-7일부터 매일 발송',
    notifDayOf: '당일 미처리 알림',
    notifDayOfDesc: '출금일 당일 미기록 시 발송',
    notifMonthlyReport: '📊 월간 리포트 공개',
    notifMonthlyDesc: '매월 1일 리포트 알림',
    notifInputRemind: '✏️ 지출 입력 리마인드',
    notifInputDesc: '점심(12:00) · 저녁(19:00)',
    socialConnect: '소셜 연동',
    btnGoogleLink: 'Google 계정으로 연동하기',
    btnLinking: '연동 중...',
    btnLinked: '연동됨 ✓',
    btnLink: '연동하기',
    noName: '이름 없음',
    btnSave: '저장',
    btnSaving: '...',
    btnCancel: '취소',
    guestBannerTitle: '게스트 계정 사용 중',
    guestBannerDesc: '로그아웃하거나 기기를 변경하면 모든 데이터가 사라져요.\nGoogle 계정으로 연동하면 영구 보관됩니다.',
    guestBannerBtnLink: 'Google로 연동하고 데이터 보존',
    logoutLabel: '로그아웃',
    logoutLoading: '로그아웃 중...',
    withdrawGuest: '게스트 탈퇴',
    withdraw: '회원 탈퇴',
    withdrawConfirmTitle: '탈퇴하시겠어요?',
    withdrawConfirmDesc: '모든 지출 내역, 자산 설정, 구독 이력이 삭제돼요',
    withdrawBtnConfirm: '계속',
    withdrawBtnCancel: '취소',
    withdrawVerifyTitle: '닉네임을 입력해 본인 확인',
    withdrawVerifyDesc: (name: string) => `"${name}"을 그대로 입력해주세요`,
    withdrawBtnDo: '탈퇴하기',
    guestLogoutTitle: '⚠️ 로그아웃 전에 확인해요',
    guestLogoutDesc1: '게스트 계정에서 로그아웃하면',
    guestLogoutDesc2: '모든 기록·설정 데이터가 영구 삭제',
    guestLogoutDesc3: '됩니다.',
    guestLogoutDesc4: 'Google 계정으로 연동하면 데이터를 보존할 수 있어요.',
    guestLogoutBtnLink: 'Google로 연동하고 데이터 보존',
    guestLogoutBtnLogout: (loading: boolean) => loading ? '처리 중...' : '데이터 삭제 후 로그아웃',
    guestLogoutBtnCancel: '취소',
  },

  // ────────────────────────────────────────
  // 지출추가 — AddExpenseForm
  // ────────────────────────────────────────
  addExpense: {
    tabExpense: '💸 지출',
    tabIncome: '💰 수입',
    labelAmount: '금액 *',
    labelNameExpense: '상호명 / 항목명 *',
    labelNameIncome: '항목명 * (예: 월급, 용돈)',
    namePlaceholderExpense: '예) 스타벅스',
    namePlaceholderIncome: '예) 월급',
    labelCategory: '카테고리 *',
    labelDate: '날짜 *',
    labelPaymentExpense: '결제수단',
    labelPaymentIncome: '수입 경로',
    labelMemo: '메모 (선택)',
    memoPh: '간단히 남겨보세요',
    btnSaveExpense: '지출 저장',
    btnSaveIncome: '수입 저장',
    btnSaving: '저장 중...',
    errAmount: '금액을 입력해주세요',
    errName: '항목명을 입력해주세요',
    errPayment: '결제 / 수입 수단을 선택해주세요',
    errSave: '저장 중 오류가 발생했어요',
    toastOffline: '임시 저장했어요. 인터넷 연결 후 자동 반영돼요',
    toastSavedExpense: '지출이 저장됐어요!',
    toastSavedIncome: '수입이 저장됐어요!',
  },

  // ────────────────────────────────────────
  // 온보딩 — OnboardingForm
  // ────────────────────────────────────────
  onboarding: {
    btnSkip: '건너뛰기',
    btnNext: '다음 →',
    btnPrev: '← 이전',
    btnStart: '시작하기 🎉',
    btnStartSaving: '저장 중...',
    nameTitle: '안녕하세요! 😊',
    nameSubtitle: '어떻게 불러드릴까요?',
    nameBtnShuffle: '🔀 다른 이름',
    nameOrLabel: '또는 직접 입력',
    nameInputPh: '닉네임 입력 (선택)',
    nameDefaultHint: (name: string) => `입력하지 않으면 "${name}"으로 시작해요`,
    themeTitle: '나만의 감성을 골라봐요 🎨',
    themeSubtitle: '언제든지 설정에서 바꿀 수 있어요',
    themeMoreNote: '✨ 더 많은 테마는 설정에서 만나보세요!',
    themePremiumTitle: '프리미엄 전용 테마예요',
    themePremiumDesc: '설정 탭에서 프리미엄으로 업그레이드하면 모든 테마를 자유롭게 사용할 수 있어요',
    themeBtnDefault: '기본 테마로 계속',
    incomeTitle: '월 수입을 알려줘요 💰',
    incomeSubtitle: '세후 실수령 기준이에요. 나중에 바꿀 수 있어요.',
    incomeLabel: '월 수입 (세후)',
    incomeSuffix: '만 원',
    incomeHint: (v: number) => `= ${v.toLocaleString()}원`,
    goalTitle: '저축 목표가 있나요? 🎯',
    goalSubtitle: '매달 이만큼 저축하는 게 목표예요',
    goalLabel: '월 저축 목표',
    goalLabelOpt: '(선택)',
    goalSuffix: '만 원',
    goalHint: (v: number) => `= ${v.toLocaleString()}원`,
    goalTip: '💡 입력하면 홈 화면에서 저축 달성률을 볼 수 있어요',
    budgetTitle: '예산을 설정해봐요 📋',
    budgetSubtitle: '나중에 예산 탭에서 바꿀 수 있어요',
    budgetTabAI: '✨ AI 추천',
    budgetTabManual: '직접 입력',
    budgetAIBasis: (income: string) => `월 수입 ${income}만원 기준으로 예산을 추천받아요`,
    budgetAINoIncome: '기본 비율로 예산을 추천해드릴게요',
    budgetBtnAI: '✨ AI 추천 받기',
    budgetBtnAILoading: '분석 중...',
    budgetFallbackNote: '💡 지출 기록이 없어 기본 비율으로 추천했어요',
    budgetUnitWon: '원',
    assetsTitle: '통장을 등록해봐요 🏦',
    assetsSubtitle: '잔액을 관리하고 싶은 계좌예요',
    assetsOpt: '(선택)',
    assetsAddTitle: '계좌 추가',
    assetsNamePh: '계좌 이름 (예: 주거래통장)',
    assetsBankPh: '은행명 (예: 카카오뱅크)',
    assetsBalancePh: '현재 잔액',
    assetsBalanceSuffix: '원',
    assetsBtnAdd: (adding: boolean) => adding ? '추가 중...' : '+ 계좌 추가',
    cardsTitle: '카드를 등록해봐요 💳',
    cardsSubtitle: '지출 입력 시 결제수단으로 사용해요',
    cardsOpt: '(선택)',
    cardsAddTitle: '카드 추가',
    cardsNamePh: '카드 이름 (예: 신한카드)',
    cardsBankPh: '카드사 (예: 신한)',
    cardsBtnAdd: (adding: boolean) => adding ? '추가 중...' : '+ 카드 추가',
    fixedTitle: '고정비를 등록해봐요 📌',
    fixedSubtitle: '매달 나가는 돈을 한 번에 정리해요',
    fixedOpt: '(선택)',
    fixedTip: '💡 월세·통신비·구독료·적금 등 매달 반복되는 지출을 등록하는 곳이에요',
    fixedExpenseLabel: '고정지출',
    fixedSavingLabel: '고정저축',
    fixedDueSuffix: (day: number) => `매월 ${day}일`,
    fixedAddTitle: '고정비 추가',
    fixedNamePh: '이름 (예: 월세, 넷플릭스)',
    fixedAmountPh: '금액',
    fixedAmountSuffix: '원',
    fixedDuePh: '납부일',
    fixedDueDaySuffix: '일',
    fixedBtnAdd: (adding: boolean) => adding ? '추가 중...' : '+ 고정비 추가',
    catsTitle: '카테고리를 확인해요 🏷️',
    catsSubtitle: '필요하면 추가·삭제할 수 있어요',
    catsTip: '💡 다른 카테고리는 설정 탭에서도 관리할 수 있어요',
    catsIncomeTip: '💡 수입 카테고리는 수입 기록 시 사용돼요',
    catsNewPh: '새 카테고리 이름',
    catsBtnAdd: '추가',
    completeSuffix: '님,',
    completeTitle: 'Spenlog가 준비됐어요!',
    completeSubtitle: '오늘부터 소비를 기록해봐요.',
    errSave: (msg: string) => `저장 오류: ${msg}`,
  },

  // ────────────────────────────────────────
  // AI 프롬프트 — api/ai-input/route.ts
  // ────────────────────────────────────────
  aiPrompt: {
    errNoAmount: '금액을 인식하지 못했어요. 예) 아아 3000원 / 커피 삼천원',
    defaultName: '항목',
    defaultCategory: '예비비',
  },
} as const
